@startuml

class Organization <<kind>> {
    brandName
    officialName
    category : Organization Category
}
enum "Organization Category" <<enumeration>> {
    REGULAR
    NON_PROFIT
    GOVERNAMENTAL
}

@enduml