import { OntoumlElement } from '../ontouml_element';
import { OntoumlType } from '../ontouml_type';
import { Class } from './class';
import { ClassStereotype, OntologicalNature, PropertyStereotype, RelationStereotype } from './constants';
import { Generalization } from './generalization';
import { GeneralizationSet } from './generalization_set';
import { Literal } from './literal';
import { ModelElement } from './model_element';
import { Package } from './package';
import { Property } from './property';
import { Relation } from './relation';

export interface ModelElementContainer {
  getAllPackages(): Package[];
  getAllClasses(): Class[];
  getAllEnumerations(): Class[];
  getAllAttributes(): Property[];
  getAllLiterals(): Literal[];
  getAllRelations(): Relation[];
  getAllRelationEnds(): Property[];
  getAllGeneralizations(): Generalization[];
  getAllGeneralizationSets(): GeneralizationSet[];
  getAllModelElements(): ModelElement[];
  getAllContentsByType(type: OntoumlType | OntoumlType[]): OntoumlElement[];
  getAllAttributesByStereotype(stereotype: PropertyStereotype | PropertyStereotype[]): Property[];
  getAllClassesByStereotype(stereotype: ClassStereotype | ClassStereotype[]): Class[];
  getAllRelationsByStereotype(stereotype: RelationStereotype | RelationStereotype[]): Relation[];
  getAllClassesWithRestrictedToContainedIn(nature: OntologicalNature | OntologicalNature[]): Class[];
  getClassesWithTypeStereotype(): Class[];
  getClassesWithHistoricalRoleStereotype(): Class[];
  getClassesWithHistoricalRoleMixinStereotype(): Class[];
  getClassesWithEventStereotype(): Class[];
  getClassesWithSituationStereotype(): Class[];
  getClassesWithCategoryStereotype(): Class[];
  getClassesWithMixinStereotype(): Class[];
  getClassesWithRoleMixinStereotype(): Class[];
  getClassesWithPhaseMixinStereotype(): Class[];
  getClassesWithKindStereotype(): Class[];
  getClassesWithCollectiveStereotype(): Class[];
  getClassesWithQuantityStereotype(): Class[];
  getClassesWithRelatorStereotype(): Class[];
  getClassesWithQualityStereotype(): Class[];
  getClassesWithModeStereotype(): Class[];
  getClassesWithSubkindStereotype(): Class[];
  getClassesWithRoleStereotype(): Class[];
  getClassesWithPhaseStereotype(): Class[];
  getClassesWithEnumerationStereotype(): Class[];
  getClassesWithDatatypeStereotype(): Class[];
  getClassesWithAbstractStereotype(): Class[];
  getClassesRestrictedToFunctionalComplex(): Class[];
  getClassesRestrictedToCollective(): Class[];
  getClassesRestrictedToQuantity(): Class[];
  getClassesRestrictedToMode(): Class[];
  getClassesRestrictedToIntrinsicMode(): Class[];
  getClassesRestrictedToExtrinsicMode(): Class[];
  getClassesRestrictedToQuality(): Class[];
  getClassesRestrictedToRelator(): Class[];
}
