import Ajv from 'ajv';
import addFormats from 'ajv-formats';
import { Class, ENUMERATION, Project } from '../../src';

const schema = require('ontouml-schema');

describe('Test Class serialization', () => {
  const ajv = new Ajv();
  const validator = addFormats(ajv).compile(schema);
  let proj: Project;
  let c: Class;

  beforeEach(() => {
    proj = new Project();
  });

  it('A default class generated by the builder should validate against the schema', () => {
    c = proj.classBuilder().build();
    expect(validator(c.toJSON())).toBeTruthy();
  });

  it('A class with an attribute should validate against the schema', () => {
    c = proj.classBuilder().build();
    c.propertyBuilder().build();
    expect(validator(c.toJSON())).toBeTruthy();
  });

  it('A enumeration class with a literal should validate against the schema', () => {
    c = proj.classBuilder().build();
    c.stereotype = ENUMERATION;
    c.literalBuilder().build();
    expect(validator(c.toJSON())).toBeTruthy();
  });

  it('A class with a «kind» stereotype should validate against the schema', () => {
    c = proj.classBuilder().kind().build();
    expect(validator(c.toJSON())).toBeTruthy();
  });

  it('A class with a custom stereotype should validate against the schema', () => {
    c = proj.classBuilder().stereotype('my-stereotype').build();
    expect(validator(c.toJSON())).toBeTruthy();
  });

  it('A class with `order = 2` should validate against the schema', () => {
    c = proj.classBuilder().order(2).build();
    expect(validator(c.toJSON())).toBeTruthy();
  });
});
