export enum OntoumlType {
  PROJECT = "Project",
  PACKAGE = "Package",
  CLASS = "Class",
  BINARY_RELATION = "BinaryRelation",
  NARY_RELATION = "NaryRelation",
  GENERALIZATION = "Generalization",
  GENERALIZATION_SET = "GeneralizationSet",
  PROPERTY = "Property",
  LITERAL = "Literal",
  NOTE = "Note",
  NOTE_LINK = "NoteLink",
  DIAGRAM = "Diagram",
  CLASS_VIEW = "ClassView",
  BINARY_RELATION_VIEW = "BinaryRelationView",
  NARY_RELATION_VIEW = "NaryRelationView",
  GENERALIZATION_VIEW = "GeneralizationView",
  GENERALIZATION_SET_VIEW = "GeneralizationSetView",
  PACKAGE_VIEW = "PackageView",
  NOTE_VIEW = "NoteView",
  RECTANGLE = "Rectangle",
  DIAMOND = "Diamond",
  TEXT = "Text",
  PATH = "Path",
}
