export enum VerificationIssueCode {
  class_identity_provider_specialization = 'class_identity_provider_specialization',
  class_missing_nature_restrictions = 'class_missing_nature_restrictions',
  class_missing_identity_provider = 'class_missing_identity_provider',
  class_missing_is_extensional = 'class_missing_is_extensional',
  class_missing_is_powertype = 'class_missing_is_powertype',
  class_missing_order = 'class_missing_order',
  class_multiple_identity_providers = 'class_multiple_identity_providers',
  class_not_unique_stereotype = 'class_not_unique_stereotype',
  class_invalid_ontouml_stereotype = 'class_invalid_ontouml_stereotype',
  class_non_enumeration_with_literals = 'class_non_enumeration_with_literals',
  class_enumeration_with_properties = 'class_enumeration_with_properties',
  class_incompatible_natures = 'class_incompatible_natures',
  generalization_inconsistent_specialization = 'generalization_inconsistent_specialization',
  generalization_incompatible_natures = 'generalization_incompatible_natures',
  generalization_incompatible_enumeration = 'generalization_incompatible_enumeration',
  generalization_incompatible_datatype = 'generalization_incompatible_datatype',
  generalization_incompatible_class_rigidity = 'generalization_incompatible_class_rigidity',
  generalization_incompatible_class_sortality = 'generalization_incompatible_class_sortality',
  generalization_incompatible_general_and_specific_types = 'generalization_incompatible_general_and_specific_types',
  generalization_circular = 'generalization_circular',
  generalization_incompatible_relation_type = 'generalization_incompatible_relation_type',
  relation_multiple_stereotypes = 'relation_multiple_stereotypes',
  relation_missing_is_read_only = 'relation_missing_is_read_only',
  relation_improper_derivation = 'relation_improper_derivation'
}
